index:
    path: /{name}
    defaults:
      _controller: 'App\Controller\DefaultController::index'
      name: 'World'

# Depends on sensio/framework-extra-bundle:^3.0 and doctrine/annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
